"""
build_trends_consumos.py — Capítulo 06 CONSUMOS

SOLO DATOS. Todo el layout vive en trends_deck_engine.py (el "CSS" central).
Para cambiar espaciado/tamaños/fuentes NO toques este archivo — edita el motor
y TODOS los capítulos se actualizan idénticos.
"""

from pathlib import Path
from trends_deck_engine import build_deck

BASE        = Path("/Users/jeremyrodriguez/Documents/Cerebro/Código Casa/Team Trends CC")
SCREENSHOTS = BASE / "screenshots" / "trends-consumos"
OUTPUT      = BASE / "outputs" / "trends-consumos-forecast.pptx"

# ─── Macros ─────────────────────────────────────────────────────────────────
M1_N = "MACRO 1"; M1_NAME = "INVENTOLOGÍA DE LA ADULTEZ"
M1_TAG = "Un mundo en crisis está reescribiendo qué significa ser adulto y formar familia."
M2_N = "MACRO 2"; M2_NAME = "LOS HERNÁNDEZ ARE PROMPTED"
M2_TAG = "El dominicano ya entró al mundo prompteado. Solo no lo nombra así."
M3_N = "MACRO 3"; M3_NAME = "ALGORITMO DEL HOGAR"
M3_TAG = "El feed se sentó en la mesa y nadie le ofreció silla."

DIVIDERS = [
    (1, M1_NAME, M1_TAG),
    (2, M2_NAME, M2_TAG),
    (3, M3_NAME, M3_TAG),
]

MICROS = [
    # ── Macro 1 ──────────────────────────────────────────────────────────────
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="El 'no compré nada este mes' reemplazó al estreno como flex: el underconsumption core hizo del armario mínimo una señal de estatus.",
         fenomeno="Antes presumías lo que estrenabas. Ahora hay toda una estética de presumir lo contrario: el armario que repites, el 'what I didn't buy', el reto de cero compras. La austeridad se volvió performance. No es que falte la plata — es que mostrar que no gastas se lee como criterio, como madurez financiera.",
         hashtags="#underconsumptioncore · #nobuy2025 · #lowbuy · #deinfluencing · #mindfulspending",
         triggers=[
             dict(stat="37%",     desc="De Gen Z planea ahorrar más, 29% invertir; el pivote se lee como corrección, no restricción.", source="YouGov · 2025"),
             dict(stat="6B+",     desc="Views de #underconsumptioncore documentado como contra-tendencia viral al deinfluencing.", source="Visibrain / TikTok · 2025"),
             dict(stat="No-Buy",  desc="'De Labubu al No-Buy': los virales de consumo chocan con la realidad económica.", source="Girls United / Essence · 2025"),
         ],
         signals=[
             dict(png="macro-1-1-tiktok-underconsumptioncore-1.png",
                  caption="'underconsumption core / all my furniture' — armario mínimo como flex aspiracional en TikTok.",
                  source="TikTok @chelsychristina · 2024",
                  url="https://www.tiktok.com/@chelsychristina/video/7395747286262828319"),
             dict(png="macro-1-1-tiktok-underconsumptioncore-2.png",
                  caption="'Underconsumption is a CHOICE you make every day' — el no-comprar como performance intencional.",
                  source="TikTok @breakyourbudget · 2025",
                  url="https://www.tiktok.com/@breakyourbudget/video/7502132957872819502"),
             dict(png="macro-1-1-girlsunited-labubu-nobuy.png",
                  caption="De Labubu al No-Buy: virales de consumo chocan con la realidad económica — el ciclo se acelera.",
                  source="Girls United / Essence · 2025",
                  url="https://girlsunited.essence.com/feedback/from-labubu-to-no-buy-how-viral-trends-are-colliding-with-economic-reality/"),
         ]),
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="El dupe salió del clóset: comprar la versión barata del lujo dejó de dar pena y pasó a presumirse como inteligencia de compra.",
         fenomeno="El dupe vivía escondido. Era el truco que no decías. Ahora es el contenido: 'dupe vs original', reseñas lado a lado, el ahorro presumido como logro. La marca cara ya no compite solo con otras marcas — compite con su propia copia, legitimada por el feed.",
         hashtags="#dupe · #dupecheck · #lookforless · #amazonfinds · #dupes",
         triggers=[
             dict(stat="6B",    desc="Views de #dupe en TikTok; el hashtag convirtió la copia en categoría de contenido.", source="TikTok Creative Center · 2025"),
             dict(stat="70%",   desc="De Gen Z dice haber comprado dupes 'ocasional o muy regularmente' el último año.", source="Business Insider / YouGov · 2025"),
             dict(stat="Shift", desc="Dupe culture como 'aspirational shift' de Gen Z: el estatus pasa del logo a la astucia.", source="Luxury Tribune · 2025"),
         ],
         signals=[
             dict(png="macro-1-2-tiktok-dupe-7546363805240921399.png",
                  caption="'Viral perfumes — Dupe VS Original' — reseña lado a lado de alternativas masivas vs. lujo.",
                  source="TikTok @perfumesiren · 2025",
                  url="https://www.tiktok.com/@perfumesiren/video/7546363805240921399"),
             dict(png="macro-1-2-tiktok-dupe-7526268718016400671.png",
                  caption="Top 5 drugstore dupes de maquillaje high-end — la astucia del consumidor como contenido.",
                  source="TikTok @mannymua733 · 2025",
                  url="https://www.tiktok.com/@mannymua733/video/7526268718016400671"),
             dict(png="macro-1-2-tiktok-dupe-mikayla-mco.png",
                  caption="'MCO Beauty vs. Original Products' — el dupe legitimado por una mega-creadora de belleza.",
                  source="TikTok @mikaylanogueira · 2025",
                  url="https://www.tiktok.com/@mikaylanogueira/video/7496555296874188074"),
         ]),
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="Lo usado dejó de ser cosa de pobre: en LATAM la reventa pasó de necesidad a elección de criterio, y el preowned se volvió canal aspiracional.",
         fenomeno="Comprar usado cargaba un estigma de clase. Eso se está cayendo en LATAM. El thrift haul es contenido, vender lo propio para financiar lo nuevo es práctica normal, y comprar lujo autenticado de segunda mano se lee como gusto, no como falta de plata.",
         hashtags="#thrifthaul · #segundamano · #preloved · #reventa · #thriftflip",
         triggers=[
             dict(stat="US$17.9B", desc="Ropa segunda mano LATAM para 2031 vs US$5.2B en 2025, CAGR 22.8%.", source="6WResearch / Mobility Foresights · 2025"),
             dict(stat="83%",      desc="De Gen Z global compró o quiere comprar usado — 10.7 pts sobre el promedio general.", source="Cognitive Market Research · 2025"),
             dict(stat="LATAM",    desc="Outlook reventa LATAM 2026: economía empuja el usado a opción mainstream.", source="BankVogue · 2026"),
         ],
         signals=[
             dict(png="macro-1-3-tiktok-thrifthaul-7546587734941404471.png",
                  caption="Thrift haul de la semana — botín visual de reventa aspiracional en LATAM.",
                  source="TikTok @metalromantic · 2025",
                  url="https://www.tiktok.com/@metalromantic/video/7546587734941404471"),
             dict(png="macro-1-3-tiktok-thrifthaul-7457656349103623466.png",
                  caption="Tour de tienda #segundamano — la reventa como canal local aspiracional con #thrifthaul.",
                  source="TikTok @goldenbeetrove · 2025",
                  url="https://www.tiktok.com/@goldenbeetrove/video/7457656349103623466"),
             dict(png="macro-1-3-corotos-rd-plataforma-usados.png",
                  caption="Corotos.com.do — plataforma dominicana de segunda mano con listings de RD$10,000 a US$80,600.",
                  source="Corotos.com.do · 2026",
                  url="https://www.corotos.com.do"),
         ]),
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="'No puedo, estoy presupuestando' se volvió presumible: el loud budgeting convirtió el ahorro en performance y el gasto impulsivo en cosa de inmaduros.",
         fenomeno="Decir que no tenías plata daba pena. El loud budgeting le dio la vuelta: ahora anuncias en voz alta que no vas porque estás presupuestando, y eso te hace ver con control, no con carencia. La adultez nueva se prueba demostrando que tienes la mano en el timón.",
         hashtags="#loudbudgeting · #presupuesto · #ahorro2025 · #moneytok · #finanzaspersonales",
         triggers=[
             dict(stat="37%",    desc="De Gen Z planea ahorrar más, 29% invertir; el consumo se subordina al plan financiero.", source="YouGov · 2025"),
             dict(stat="BNPL",   desc="Inestabilidad inflacionaria LATAM empuja a estabilizar el poder de compra con instrumentos de planificación.", source="GlobeNewswire / LATAM BNPL · 2025"),
             dict(stat="Swaps",  desc="Marcas financieras como Fifth Third Bank hablan en 'loud budgeting swaps' para sonar nativas del feed.", source="TikTok @fifththirdbank · 2024"),
         ],
         signals=[
             dict(png="macro-1-4-tiktok-loudbudgeting-7451260628603473198.png",
                  caption="'2025 we are LOUD BUDGETING' — presupuestar en público como nueva señal de adultez.",
                  source="TikTok @breakyourbudget · 2025",
                  url="https://www.tiktok.com/@breakyourbudget/video/7451260628603473198"),
             dict(png="macro-1-4-tiktok-loudbudgeting-7340699620734995754.png",
                  caption="Loud budgeting swaps: marca financiera adopta el lenguaje viral para normalizar el 'no' al gasto social.",
                  source="TikTok @fifththirdbank · 2024",
                  url="https://www.tiktok.com/@fifththirdbank/video/7337773119731584302"),
             dict(png="macro-2-0-globenewswire-latam-bnpl.png",
                  caption="BNPL LATAM +27% en 2025 a US$16.2B — instrumento de estabilización del poder de compra.",
                  source="GlobeNewswire · Febrero 2025",
                  url="https://www.globenewswire.com/news-release/2025/02/27/3033728/28124/en/Latin-America-Buy-Now-Pay-Later-Business-Report-2025-2030.html"),
         ]),
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="El gasto aspiracional se mudó del objeto a la experiencia: girl math y soft life hacen que el viaje pese más que el carro nuevo.",
         fenomeno="El nuevo capital social no se acumula en cosas, se acumula en momentos. El gasto aspiracional se corrió de electrodomésticos y lujo material a viajes, conciertos, autocuidado. La 'girl math' es el marco viral que justifica el gasto experiencial. El recuerdo rinde más que la posesión.",
         hashtags="#girlmath · #softlife · #treatculture · #selfcarespending · #experienceoverstuff",
         triggers=[
             dict(stat="66%",   desc="De la población global pagaría premium por productos alineados con sus valores.", source="Green Premium Studies · 2025"),
             dict(stat="LATAM", desc="Auge de wellness influencers que venden experiencia y servicio en live commerce LATAM.", source="Grand View Research · 2025"),
             dict(stat="Math",  desc="'Girl math' como marco viral para justificar gasto experiencial vs. material en TikTok.", source="TikTok · 2023 [HISTÓRICO]"),
         ],
         signals=[
             dict(png="macro-1-5-tiktok-girlmath-softlife-7454705982652943621.png",
                  caption="'Dear 2025' con CEO SoftLife — vivir bien como aspiración post-acumulación.",
                  source="TikTok @tashamichie124 · 2025",
                  url="https://www.tiktok.com/@tashamichie124/video/7454705982652943621"),
             dict(png="macro-1-5-tiktok-girlmath-softlife-7264583361304333611.png",
                  caption="'somehow it makes sense #girlmath' — la lógica aspiracional que convierte experiencias en inversión.",
                  source="TikTok @mckennaelianna · 2023",
                  url="https://www.tiktok.com/@mckennaelianna/video/7264583361304333611"),
             dict(png="macro-1-5-tiktok-girlmath-softlife-7276207307921313030.png",
                  caption="'Justifying purchases with GIRL MATH' — marco viral para validar gasto experiencial vs. material.",
                  source="TikTok @casandra.mazzucco · 2023",
                  url="https://www.tiktok.com/@casandra.mazzucco/video/7276207307921313030"),
         ]),
    # ── Macro 2 ──────────────────────────────────────────────────────────────
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="El agente de IA pasó de recomendarte a comprar por ti: fijas el precio objetivo y Rufus Auto-Buy ejecuta el checkout sin que toques nada.",
         fenomeno="La IA recomendaba. Ahora ejecuta. Rufus Auto-Buy compra cuando se cumplen los parámetros que tú fijaste — precio, condición, momento. El humano deja de hacer el checkout. La compra se vuelve una orden delegada bajo reglas, no un acto consciente cada vez.",
         hashtags="#aishopping · #rufus · #agenticcommerce · #shoppingassistant · #autobuy",
         triggers=[
             dict(stat="250M",   desc="Usuarios activos mensuales de Rufus (+149% YoY); quien lo usa compra 60% más.", source="Nova Analytics · 2025"),
             dict(stat="US$1T",  desc="Commerce agéntico proyectado en retail USA para 2030 (McKinsey) + US$115B adicionales por agentes.", source="McKinsey / Morgan Stanley · 2025"),
             dict(stat="Pivot",  desc="Amazon abandona Rufus y pivota a Alexa Shopping Agent que ejecuta compras autónomas.", source="CNBC · Mayo 2026"),
         ],
         signals=[
             dict(png="macro-2-1-tiktok-aishopping-7469936286556589344.png",
                  caption="#aishopping — creadores documentan cómo la IA selecciona sus compras en TikTok.",
                  source="TikTok @unique21official · 2025",
                  url="https://www.tiktok.com/@unique21official/video/7469936286556589344"),
             dict(png="macro-2-1-retailtech-rufus-ai-shopping.png",
                  caption="Rufus en acción: el agente de IA recomienda en pantalla — la batalla por la intención de compra.",
                  source="RetailTech Innovation Hub · Enero 2026",
                  url="https://retailtechinnovationhub.com/home/2026/1/5/rufus-and-the-ai-shopping-war-why-amazons-assistant-reveals-the-battle-for-customer-intent"),
             dict(png="macro-2-1-novadata-rufus-autobuy.png",
                  caption="Rufus Auto-Buy: 250M usuarios activos mensuales (+149% YoY) — quien lo usa compra 60% más.",
                  source="Nova Analytics · 2025",
                  url="https://novadata.io/resources/news/amazon-rufus-agentic-auto-buy-250-million-users"),
         ]),
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="Págalo en cuatro y no lo sientas: el BNPL borra el límite del presupuesto de la experiencia de compra y crece en LATAM como crédito para los que el banco no banca.",
         fenomeno="Partir el pago en cuotas sin tarjeta cambia cómo se siente el precio. En LATAM, donde +40% de la población carece de crédito formal, el BNPL crece como herramienta de inclusión. Mercado Pago, Addi, Kueski funcionan como crédito de facto en el checkout. Compras ahora aunque el flujo esté apretado.",
         hashtags="#bnpl · #cuotassininteres · #pagaen4 · #mercadopago · #fintechlatam",
         triggers=[
             dict(stat="US$16.2B", desc="BNPL LATAM en 2025 (+27%); +40% de la población sin crédito formal en la región.", source="LATAM BNPL Report · 2025"),
             dict(stat="Omni",     desc="BNPL se expande de e-commerce a in-store y omnicanal en 2026; super apps dominan el ecosistema.", source="GlobeNewswire · 2026"),
             dict(stat="Inclusión",desc="Mercado Pago, Kueski y Creditas diseñan cuotas para no-bancarizados — BNPL como herramienta de acceso.", source="Hope Research Group · 2025"),
         ],
         signals=[
             dict(png="macro-2-2-addi-bnpl-checkout.png",
                  caption="ADDI: 'Compra lo que quieres hoy, págalo después' — el BNPL hace invisible el límite del presupuesto.",
                  source="ADDI · 2025",
                  url="https://addi.com"),
             dict(png="macro-2-2-globenewswire-bnpl-latam-2026.png",
                  caption="BNPL LATAM 2026: expansión de e-commerce a in-store y omnicanal — super apps dominan.",
                  source="GlobeNewswire · Enero 2026",
                  url="https://www.globenewswire.com/news-release/2026/01/20/3221587/28124/en/Latin-America-Buy-Now-Pay-Later-Business-Report-2026-2031.html"),
             dict(png="macro-2-0-paymentscmi-ecommerce-rd.png",
                  caption="E-commerce RD supera US$5.2B en 2025 — PayPal (58%) y tPago (40%) lideran wallets dominicanas.",
                  source="PaymentsCMI · 2025",
                  url="https://paymentscmi.com/insights/comercio-electronico-republica-dominicana-datos-clave/"),
         ]),
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="El checkout se mudó adentro del video: TikTok Shop colapsa entretenimiento y compra, y en Brasil el GMV pasó de US$1M a US$25.7M en tres meses.",
         fenomeno="Ver y comprar eran dos momentos separados. TikTok Shop los fundió: el 'yellow basket' vive dentro del video, descubres-deseas-pagas en segundos sin salir del scroll. Ya está en cinco países de LATAM y los registros de sellers subieron +300% en México desde 2023.",
         hashtags="#tiktokshop · #tiktokmademebuyit · #socialcommerce · #compraporredes · #yellowbasket",
         triggers=[
             dict(stat="+300%",  desc="Registros de sellers TikTok Shop en México desde 2023; en Brasil GMV de US$1M a US$25.7M en 3 meses.", source="Awisee / M2E Cloud · 2025"),
             dict(stat="20%",    desc="TikTok Shop captura ~18-20% del social commerce USA; proyectado a 24.1% en 2027.", source="eMarketer · 2025"),
             dict(stat="US$20B", desc="Social commerce LATAM proyectado para 2025; +60% sigue influencers que recomiendan o venden.", source="LatAm Intersect PR · 2025"),
         ],
         signals=[
             dict(png="macro-2-3-tiktok-tiktokshop-7441997574112021806.png",
                  caption="Creador LATAM explicando TikTok Shop — el checkout integrado al video llega a vendedores locales.",
                  source="TikTok @crece.con.lamore · 2025",
                  url="https://www.tiktok.com/@crece.con.lamore/video/7441997574112021806"),
             dict(png="macro-2-3-awisee-tiktokshop-latam.png",
                  caption="TikTok Shop en MX, BR, CO, CL, PE — en Brasil GMV pasó de US$1M a US$25.7M en 3 meses.",
                  source="Awisee · 2025",
                  url="https://awisee.com/blog/tiktok-shop-in-latin-america/"),
             dict(png="macro-2-3-emarketer-tiktokshop-20pct.png",
                  caption="TikTok Shop captura ~20% del social commerce USA en 2025; proyectado a 24.1% en 2027.",
                  source="eMarketer · 2025",
                  url="https://www.emarketer.com/press-releases/tiktok-shop-makes-up-nearly-20-of-social-commerce-in-2025/"),
         ]),
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="La despensa empezó a llenarse sola: estanterías inteligentes y electrodomésticos conectados pesan el detergente y lo reordenan antes de que se acabe.",
         fenomeno="Ir a comprar lo básico era una tarea mental fija: revisar, anotar, salir. Esa tarea se está automatizando. El Dash Smart Shelf pesa el inventario y reordena solo. Lavadoras, cafeteras y electrodomésticos con Dash Replenishment integrado piden cápsulas sin que nadie lo decida.",
         hashtags="#smarthome · #autoreplenish · #subscribeandsave · #amazondash · #casainteligente",
         triggers=[
             dict(stat="US$19.99", desc="Dash Smart Shelf pesa el inventario y reordena solo con Subscribe & Save.", source="Amazon / Retail Dive · 2020"),
             dict(stat="DRS",      desc="Bosch, Toshiba, illy y Beko integran Dash Replenishment Service en sus electrodomésticos.", source="Trusted Reviews · 2018"),
             dict(stat="2×",       desc="Smart home appliances LATAM crece a doble dígito anual — la adopción ya avanza.", source="Grand View Research · 2025"),
         ],
         signals=[
             dict(png="macro-2-4-retaildive-amazon-dash-shelf.png",
                  caption="Amazon Dash Smart Shelf (US$19.99) — pesa el inventario y reordena solo vía Subscribe & Save.",
                  source="Retail Dive · 2020",
                  url="https://www.retaildive.com/news/amazon-releases-dash-smart-shelf-for-consumers-small-businesses/588465/"),
             dict(png="macro-2-4-trustedreviews-amazon-drs-appliances.png",
                  caption="Bosch HomeConnect con Amazon DRS: el electrodoméstico que reordena jabón y cápsulas solo.",
                  source="Trusted Reviews · 2018",
                  url="https://www.trustedreviews.com/news/amazon-dash-replenishment-service-3514666"),
             dict(png="macro-2-5-grandviewresearch-livecommerce-latam.png",
                  caption="Smart home appliances LATAM creciendo a doble dígito anual — la automatización doméstica avanza.",
                  source="Grand View Research · 2025",
                  url="https://www.grandviewresearch.com/industry-analysis/latin-america-live-commerce-market-report"),
         ]),
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="Comprar en vivo se volvió evento: el live shopping convierte hasta el 30% de quien mira (vs 2-3% del e-commerce) y 64% de LATAM asiste a sesiones cada mes.",
         fenomeno="El live shopping vuelve el stream un piso de venta. La oferta-relámpago, el drop cronometrado, el chat en tiempo real — todo empuja a comprar ahí mismo, empujado por escasez y comunidad. En LATAM 64% asiste a sesiones mensualmente. La urgencia social hace el trabajo que la página de producto nunca pudo.",
         hashtags="#liveshopping · #livecommerce · #ventaenvivo · #droplive · #tiktoklive",
         triggers=[
             dict(stat="US$32B",  desc="Live commerce LATAM para 2033 vs US$3.87B en 2024, CAGR 27.2%; Brasil +90% anual.", source="Grand View Research · 2025"),
             dict(stat="10×",     desc="McKinsey: conversión en live shopping hasta 10x la del e-commerce convencional.", source="McKinsey / Yavendio · 2025"),
             dict(stat="64%",     desc="De consumidores LATAM asiste a sesiones de live shopping mensualmente; conversión hasta 30%.", source="Yavendio · 2025"),
         ],
         signals=[
             dict(png="macro-2-5-yavendio-livecommerce-latam-stats.png",
                  caption="64% de LATAM asiste a live shopping mensual; conversión hasta 30% vs. 2-3% e-commerce.",
                  source="Yavendio · 2025",
                  url="https://www.yavendio.com/en/blog/live-commerce-latam-estadisticas"),
             dict(png="macro-2-5-grandviewresearch-livecommerce-latam.png",
                  caption="Live commerce LATAM: US$3.87B (2024) → US$32.08B (2033), CAGR 27.2%; Brasil +90% anual.",
                  source="Grand View Research · 2025",
                  url="https://www.grandviewresearch.com/industry-analysis/latin-america-live-commerce-market-report"),
             dict(png="macro-2-3-tiktok-tiktokshop-7441997574112021806.png",
                  caption="Creador LATAM montando venta en TikTok — el live como tienda: entretenimiento + checkout.",
                  source="TikTok @crece.con.lamore · 2025",
                  url="https://www.tiktok.com/@crece.con.lamore/video/7441997574112021806"),
         ]),
    # ── Macro 3 ──────────────────────────────────────────────────────────────
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="TikTok no te sugiere, te obliga: un video agota góndolas en días, y Sol de Janeiro pasó de viral a +US$1B mientras Labubu llegaba a US$150K en subasta.",
         fenomeno="El algoritmo fabrica must-haves que vacían el stock en días. Sol de Janeiro acumuló +850M de views y triplicó ventas. Stanley y Labubu agotaron góndolas por puro hype. El deseo no lo programa la necesidad — lo programa el feed. Lo compras para estar adentro, no para usarlo.",
         hashtags="#tiktokmademebuyit · #viralproduct · #amazonmusthaves · #soldout · #restock",
         triggers=[
             dict(stat="15%",    desc="De consumidores globales compra solo porque algo es tendencia en TikTok.", source="SAP Emarsys · 2025"),
             dict(stat="+US$1B", desc="Sol de Janeiro: +850M views, ventas triplicadas a +US$1B; Labubu llegó a US$150K en subasta.", source="Free Yourself / UC San Diego · 2025"),
             dict(stat="Top",    desc="Ranking de productos TikTok más vendidos 2025 — virales que agotan stock en días.", source="Accio · 2025"),
         ],
         signals=[
             dict(png="macro-3-1-tiktok-tiktokmademebuyit-7470330136718527777.png",
                  caption="#tiktokmademebuyit — el hashtag que acumula 80B de views documenta cada must-have del feed.",
                  source="TikTok @unique21official · 2025",
                  url="https://www.tiktok.com/@unique21official/video/7470330136718527777"),
             dict(png="macro-3-4-freeyourself-soldejaneiro-viral.png",
                  caption="Sol de Janeiro: +850M views TikTok, ventas triplicadas a +US$1B — el frasco diseñado para el feed.",
                  source="FreeYourself · 2025",
                  url="https://freeyourself.com/blogs/news/tiktok-viral-perfume-sales-stats"),
             dict(png="macro-3-1-accio-top-tiktok-products-page.png",
                  caption="Ranking de productos TikTok más vendidos 2025 — el feed como árbitro del must-have.",
                  source="Accio · 2025",
                  url="https://www.accio.com/business/top-selling-tiktok-products"),
         ]),
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="La suegra que decía qué comprar para la casa ahora es una family influencer: +60% de LATAM le copia la despensa a quien la mostró en cámara.",
         fenomeno="El consejo de qué sirve para la casa venía de la familia. Ahora viene del family/home influencer. La casa compra lo que la creadora-vecina enseñó: replica su despensa, su decoración, su Amazon storefront como lista de compras. La autoridad de consumo doméstico migró del consejo familiar al grid.",
         hashtags="#homeinfluencer · #amazonstorefront · #momtok · #compracomoella · #hometok",
         triggers=[
             dict(stat="+60%",  desc="De LATAM sigue influencers que recomiendan o venden productos.", source="LatAm Intersect PR · 2025"),
             dict(stat="Sweet", desc="Micro-influencers (10K-100K) en el sweet spot de purchase intent; CPMs caen >50% YoY.", source="JoinStatus / Influencer Marketing Hub · 2025"),
             dict(stat="Top 1K",desc="HypeTrace ya rastrea el top 1,000 de creadores TikTok en RD — influencer marketing mainstream local.", source="StarNgage / HypeTrace · 2025"),
         ],
         signals=[
             dict(png="macro-3-2-tiktok-momtok-amazon-storefront-7511087614015966495.png",
                  caption="'Linked in my Amazon storefront #momtok #shoppinghaul' — el hogar como vitrina de compra curada.",
                  source="TikTok @__jbarsty · 2025",
                  url="https://www.tiktok.com/@__jbarsty/video/7511087614015966495"),
             dict(png="macro-3-2-hypetrace-top-tiktok-rd.png",
                  caption="Top 1,000 TikTok RD — la comunidad de influencers locales que dicta el consumo doméstico dominicano.",
                  source="HypeTrace · 2025",
                  url="https://hypetrace.com/top/tiktok/dominican-republic/"),
             dict(png="macro-3-2-latamintersect-social-ecommerce.png",
                  caption="+60% de LATAM sigue influencers que recomiendan o venden — el grid reemplaza al consejo familiar.",
                  source="LatAm Intersect PR · 2025",
                  url="https://latamintersectpr.com/2025-e-commerce-trends-social-medias-impact-on-latin-american-consumer-behavior/"),
         ]),
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="Hoy estatus, mañana cringe: el algoritmo comprime la vida útil del objeto, y el Stanley que reinó en 2023 quedó 'out' cuando llegó el Owala.",
         fenomeno="El feed acelera la muerte cultural del producto. Lo que volvió deseable — el Stanley — muere en meses cuando aparece el siguiente — el Owala. El consumidor compra-descarta al ritmo del trend, no del uso. El producto no se gasta — se vuelve viejo culturalmente.",
         hashtags="#outvsin · #cringe · #trendcycle · #microtrend · #hypecycle",
         triggers=[
             dict(stat="Stanley", desc="Stanley reinó en 2023 por hype y escasez; en 2024 quedó 'out' desplazado por Owala.", source="Accio · 2025"),
             dict(stat="Hype →",  desc="Labubu pasó de hype récord a caída de valor de reventa al desinflarse el trend.", source="Girls United / Essence · 2025"),
             dict(stat="15%",     desc="Compra puramente por tendencia — base estructural de un consumo de vida cultural corta.", source="SAP Emarsys · 2025"),
         ],
         signals=[
             dict(png="macro-3-3-girlsunited-labubu-resale-drop.png",
                  caption="Labubu: de récord de reventa a valor caído al desinflarse el trend — el algoritmo crea y destruye el deseo.",
                  source="Girls United / Essence · 2025",
                  url="https://girlsunited.essence.com/feedback/from-labubu-to-no-buy-how-viral-trends-are-colliding-with-economic-reality/"),
             dict(png="macro-3-3-accio-stanley-owala-trendcycle.png",
                  caption="El ciclo de hype: Stanley reinó en 2023, Owala lo desplazó en 2024 — el feed comprime la vida útil.",
                  source="Accio · 2025",
                  url="https://www.accio.com/business/tik-tok-trending-products"),
             dict(png="macro-3-3-tiktok-whats-next-2025-report.png",
                  caption="TikTok What's Next 2025 — el reporte de tendencias que anticipa qué productos fabricará el algoritmo.",
                  source="TikTok Newsroom · 2025",
                  url="https://newsroom.tiktok.com/en-us/tiktok-whats-next-2025-trend-report-us"),
         ]),
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="El producto ahora se diseña para grabarse: el empaque con momento ASMR y el unboxing viral llegan antes que la función, y la grababilidad es la nueva feature.",
         fenomeno="La marca diseña empaque y producto pensando en cómo se ve en cámara. El unboxing grabable, el ASMR de apertura, el frasco 'estético' preceden a la función. Sol de Janeiro es el caso central — un perfume que rinde como contenido antes que como producto. Lo grabable se volvió una feature de venta.",
         hashtags="#unboxing · #asmrunboxing · #packaging · #aesthetic · #satisfying",
         triggers=[
             dict(stat="+US$1B", desc="Sol de Janeiro: +850M views TikTok, ventas triplicadas — el frasco diseñado para el feed.", source="Free Yourself · 2025"),
             dict(stat="ASMR",   desc="#unboxing y #asmr como motores de descubrimiento de producto: el packaging es el contenido.", source="TikTok Creative Center · 2025"),
             dict(stat="Blind",  desc="Juguetes coleccionables como Labubu y blind boxes diseñados para el unboxing viral.", source="Accio · 2025"),
         ],
         signals=[
             dict(png="macro-3-4-tiktok-thrift-unboxing-7569567092769443094.png",
                  caption="#thrift2ship — reseller que graba el empaque y envío: el packaging ES el contenido.",
                  source="TikTok @thrift2ship1 · 2025",
                  url="https://www.tiktok.com/@thrift2ship1/video/7569567092769443094"),
             dict(png="macro-3-4-freeyourself-soldejaneiro-viral.png",
                  caption="Sol de Janeiro: el frasco diseñado para el feed — +850M views y ventas x3 a +US$1B.",
                  source="FreeYourself · 2025",
                  url="https://freeyourself.com/blogs/news/tiktok-viral-perfume-sales-stats"),
             dict(png="macro-3-4-accio-labubu-blindbox-toy.png",
                  caption="Labubu blind box — el producto cuyo valor es el momento de apertura: diseñado para ser grabado.",
                  source="Accio · 2025",
                  url="https://www.accio.com/business/tiktokhotsellingtoy"),
         ]),
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="Comprar es contenido: el haul volvió la compra un ritual de grabación, donde se compra para mostrar el 'qué me compré' y la audiencia mira, desea y replica.",
         fenomeno="El haul convirtió el acto de comprar en formato de contenido. Se compra para grabar el 'qué me compré', no solo para usar. El 'come shopping with me', el shopping vlog — el gasto se performa en público y se vuelve capital social. La audiencia que mira desea y replica.",
         hashtags="#haul · #comeshoppingwithme · #whatibought · #shoppingvlog · #grwmshopping",
         triggers=[
             dict(stat="Gen Z",  desc="TikTok moldea las compras de Gen Z como práctica cultural: haul, GRWM-shopping.", source="YR Media · 2025"),
             dict(stat="#haul",  desc="'come shopping with me' como formatos masivos de contenido-compra en TikTok.", source="TikTok Creative Center · 2025"),
             dict(stat="64%",    desc="De LATAM asiste a live shopping mensual — comprar es entretenimiento, no solo transacción.", source="Grand View / Yavendio · 2025"),
         ],
         signals=[
             dict(png="macro-3-5-tiktok-haul-7558965114267782422.png",
                  caption="#vintedhaul #thrifthaul — comprar para grabar: la audiencia mira, desea y replica.",
                  source="TikTok @evameganosova · 2025",
                  url="https://www.tiktok.com/@evameganosova/video/7558965114267782422"),
             dict(png="macro-3-5-tiktok-haul-7552292928236915989.png",
                  caption="#thrifthaul — el ritual de comprar como contenido: se documenta el proceso, no solo el botín.",
                  source="TikTok @mr.chiefgrief9131149 · 2025",
                  url="https://www.tiktok.com/@mr.chiefgrief9131149/video/7552292928236915989"),
             dict(png="macro-3-5-tiktok-haul-7556270397939780919.png",
                  caption="Baby thrift haul — el haul se extiende al consumo familiar: cada compra es potencial contenido.",
                  source="TikTok @ashleykateburke · 2025",
                  url="https://www.tiktok.com/@ashleykateburke/video/7556270397939780919"),
         ]),
]

if __name__ == "__main__":
    build_deck(DIVIDERS, MICROS, SCREENSHOTS, OUTPUT)
