"""
build_trends_alimentacion.py — Capítulo 04 ALIMENTACIÓN

SOLO DATOS. Todo el layout vive en trends_deck_engine.py (el "CSS" central).
Para cambiar espaciado/tamaños/fuentes NO toques este archivo — edita el motor
y TODOS los capítulos se actualizan idénticos.
"""

from pathlib import Path
from trends_deck_engine import build_deck

BASE        = Path("/Users/jeremyrodriguez/Documents/Cerebro/Código Casa/Team Trends CC")
SCREENSHOTS = BASE / "screenshots" / "trends-alimentacion"
OUTPUT      = BASE / "outputs" / "trends-alimentacion-forecast.pptx"

# ─── Macros ─────────────────────────────────────────────────────────────────
M1_N = "MACRO 1"; M1_NAME = "INVENTOLOGÍA DE LA ADULTEZ"
M1_TAG = "Un mundo en crisis está reescribiendo qué significa ser adulto y formar familia."
M2_N = "MACRO 2"; M2_NAME = "LOS HERNÁNDEZ ARE PROMPTED"
M2_TAG = "El dominicano ya entró al mundo prompteado. Solo no lo nombra así."
M3_N = "MACRO 3"; M3_NAME = "ALGORITMO DEL HOGAR"
M3_TAG = "El feed se sentó en la mesa y nadie le ofreció silla."

DIVIDERS = [
    (1, M1_NAME, M1_TAG),
    (2, M2_NAME, M2_TAG),
    (3, M3_NAME, M3_TAG),
]

MICROS = [
    # ── Macro 1 ──────────────────────────────────────────────────────────────
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="La generación sin tiempo entre semana descubrió que dos horas el domingo le devuelven la semana entera.",
         fenomeno="El joven dominicano prepara comidas el domingo para ahorrar tiempo, comer mejor y controlar lo que ingiere. No es dieta — es autonomía. El meal prep entra como ritual de adultez sin mamá-cocinera detrás.",
         hashtags="#MealPrepDominicano · #DomingoDePrep · #ControlDeLoQueComo",
         triggers=[
             dict(stat="US$36B",  desc="Mercado global de meal prep en 2026, CAGR 9.84% hasta 2035.", source="Market Reports World · 2026"),
             dict(stat="48%",     desc="De adultos ya practica meal prep; 62% de profesionales cita falta de tiempo como driver.", source="HelloFresh · 2025-2026"),
             dict(stat="4 días",  desc="@morechulaa documenta prep de 4 días con tuppers etiquetados por día de la semana.", source="TikTok @morechulaa · 2025"),
         ],
         signals=[
             dict(png="macro-1-1-tiktok-morechulaa-mealprep.png",
                  caption="@morechulaa muestra meal prep de 4 días — tuppers, arroz, proteína, etiquetas por día.",
                  source="TikTok @morechulaa · 2025",
                  url="https://www.tiktok.com/@morechulaa/video/7636986702262717704"),
             dict(png="macro-1-1-tiktok-viviankh-mealprep.png",
                  caption="@viviank.h documenta 10 sándwiches + 9 porciones congeladas — meal prep de 3 semanas.",
                  source="TikTok @viviank.h · 2025",
                  url="https://www.tiktok.com/@viviank.h/video/7620501104765177108"),
             dict(png="macro-1-0-mktreports-mealprep-market.png",
                  caption="Mercado global meal prep US$36,433M en 2026, CAGR 9.84% hasta 2035.",
                  source="Market Reports World · 2026",
                  url="https://www.marketreportsworld.com/market-reports/meal-prep-market-14713709"),
         ]),
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="Las empresas descubrieron que si el empleado come bien al mediodía rinde mejor — y el menú de almuerzo se volvió beneficio.",
         fenomeno="El trabajador de 8-5 está harto de comer calentado. Fripick deja que la empresa pague la comida y la descuente en quincena. La comida del mediodía dejó de ser problema individual — ahora es categoría B2B.",
         hashtags="#LunchMenuRD · #AlmuerzoDeTrabajo · #NegocioOyó",
         triggers=[
             dict(stat="+13%",   desc="YoY tráfico en restaurantes LATAM con lunch menus de shoulder hour pricing.", source="OpenTable / QSR Magazine · 2025-2026"),
             dict(stat="84%",    desc="Percibe los precios de alimentos como 'altos'; dos tercios prefieren opciones económicas para el almuerzo.", source="Purdue / Family Dinner Project · 2025"),
             dict(stat="RD$425", desc="Ticket promedio almuerzo corporativo vía Fripick — descuento en quincena, llega caliente en 25 min.", source="Fripick.com · 2025"),
         ],
         signals=[
             dict(png="macro-1-2-tiktok-toyantoja-noccila-lunch.png",
                  caption="@toyantoja muestra lunch en Nocciola por menos de RD$500 — dato que 'vale oro' para el trabajador.",
                  source="TikTok @toyantoja · 2025",
                  url="https://www.tiktok.com/@toyantoja/video/7610215257000234247"),
             dict(png="macro-1-2-fripick-rd-brand.png",
                  caption="Fripick RD — beneficio alimentario corporativo B2B con descuento en quincena.",
                  source="Fripick · 2025",
                  url="https://fripick.com"),
             dict(png="macro-1-0-mktreports-mealprep-market.png",
                  caption="Inflación alimentaria RD 8.03% interanual ene 2026 — el delivery se vuelve cálculo costo-tiempo.",
                  source="BCRD / Dominican Today · 2026",
                  url="https://www.marketreportsworld.com/market-reports/meal-prep-market-14713709"),
         ]),
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="Te crió con miedo a lo 'malo' y ahora comer se siente como culpa. TikTok escuchó el término y lo convirtió en trend.",
         fenomeno="La mamá que controlaba cada bocado crió hijas con relación rota con el plato. La almond mom es una cadena generacional. La adultez de esa hija inventa otra forma de comer sin la voz de mamá.",
         hashtags="#AlmondMom · #TraumasDietéticos · #ComerConCulpa",
         triggers=[
             dict(stat="30M",   desc="De americanos desarrollarán un trastorno alimentario en su vida — 2da enfermedad mental más mortal.", source="ANAD / ABC News · 2025"),
             dict(stat="42%",   desc="De niñas de 1°-3° quiere ser más delgada; 81% de niños de 10 años teme engordar.", source="ANAD Statistics · 2025"),
             dict(stat="LATAM", desc="@nour vilà lleva el trauma dietético al español bajo #almondmum — herencia sin cuestionamiento.", source="TikTok @nourvilaa · 2025"),
         ],
         signals=[
             dict(png="macro-1-3-tiktok-lielle-almondmom.png",
                  caption="@Lielle & Dee recrea rutina #almondmom — suplementos, restricción, rutina heredada sin cuestionar.",
                  source="TikTok @liellewaldman17 · 2025",
                  url="https://www.tiktok.com/@liellewaldman17/video/7617943870797630750"),
             dict(png="macro-1-3-tiktok-nourvilaa-almondmom.png",
                  caption="@nour vilà — #almondmum versión LATAM del trauma dietético en español/francés.",
                  source="TikTok @nourvilaa · 2025",
                  url="https://www.tiktok.com/@nourvilaa/video/7642383470026657046"),
             dict(png="macro-2-1-flinders-fitnessapp-disorder.png",
                  caption="Fitness apps fuelling disordered eating — foto editorial persona con teléfono, Flinders U. 2025.",
                  source="Flinders University · Feb 2025",
                  url="https://news.flinders.edu.au/blog/2025/02/22/fitness-apps-fuelling-disordered-eating/"),
         ]),
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="La diferencia entre un domingo con familia y uno solo se mide en una pregunta: ¿qué vamos a comer?",
         fenomeno="Para familias grandes el domingo es sancocho, mesa llena, todos. Para el foráneo que vive solo, es el día más difícil. La brecha no es nutricional — es emocional.",
         hashtags="#DomingoSolo · #ForáneoEnLaCapital · #SinMesaNoHayDomingo",
         triggers=[
             dict(stat="45%",   desc="De hogares come junto menos que hace una década; 84% querría compartir más comidas.", source="Simirity / FMI Foundation · 2025-2026"),
             dict(stat="17%",   desc="De familias dominicanas no comparte las horas de comida (P25 Código Casa).", source="Código Casa · 2025"),
             dict(stat="2025",  desc="World Happiness Report vincula compartir comidas con conectividad social y bienestar subjetivo.", source="World Happiness Report · 2025"),
         ],
         signals=[
             dict(png="macro-1-4-tiktok-josheilyn-foranea-capital.png",
                  caption="@Josheilyn — 'yo amo estar en mi hogar los domingos' — foránea RD viviendo en la capital.",
                  source="TikTok @josheilyndls1 · 2025",
                  url="https://www.tiktok.com/@josheilyndls1/video/7549991019169811768"),
             dict(png="macro-1-4-tiktok-mariannycorderoo-domingo.png",
                  caption="@mariannycorderoo — domingo solo en Bogotá con tostada y #amorpropio, ritual sin mesa familiar.",
                  source="TikTok @mariannycorderoo · 2025",
                  url="https://www.tiktok.com/@mariannycorderoo/video/7643570804885572882"),
             dict(png="macro-1-4-tiktok-macaseason-domingo-familiar.png",
                  caption="@María Camila — el ritual del domingo familiar completo como contraste al foráneo solo.",
                  source="TikTok @macaseason · 2025",
                  url="https://www.tiktok.com/@macaseason/video/7625031259835665685"),
         ]),
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="PedidosYa es la app #1 de food en RD: el adulto joven ya no decide qué cocinar — decide qué pedir.",
         fenomeno="La adultez tradicional cocinaba todos los días. La adultez 2026 delega el jueves a una app. No es flojera — es renegociación del rol de 'buen adulto' donde el tiempo cuesta más que la comida.",
         hashtags="#PedidosYaRD · #DeliveryEsMiMamá · #AdultoQueNoCocina",
         triggers=[
             dict(stat="#1",    desc="PedidosYa en iOS food & drink RD; 13K-21.7K descargas semanales Q1 2025.", source="Sensor Tower · Q1 2025"),
             dict(stat="50%",   desc="Precios de alimentos RD subieron entre julio 2019 y julio 2025 — delivery se vuelve cálculo.", source="BCRD / Dominican Today · 2026"),
             dict(stat="100%",  desc="Online — primer supermercado 100% digital abre en Santo Domingo; la grocería migra a app.", source="St Kitts Nevis Observer · 2025"),
         ],
         signals=[
             dict(png="macro-1-5-pedidosya-country-selector.png",
                  caption="PedidosYa selector de países — RD listada con badges App Store y Google Play.",
                  source="PedidosYa · 2026",
                  url="https://www.pedidosya.com"),
             dict(png="macro-1-5-sensortower-pedidosya-rd-chart.png",
                  caption="Bar chart Sensor Tower: PedidosYa #1 en descargas food delivery RD Q1 2025.",
                  source="Sensor Tower · Q1 2025",
                  url="https://sensortower.com/blog/2025-q1-unified-top-5-food%20delivery%20services-units-do-63da96fbe1714cfff1c1e5a1"),
             dict(png="macro-1-5-stkitts-online-super-sd.png",
                  caption="Primer supermercado 100% online en Santo Domingo — la grocería migra a app.",
                  source="St Kitts Nevis Observer · 2025",
                  url="https://www.thestkittsnevisobserver.com/first-online-only-supermarket-opens-in-santo-domingo/"),
         ]),
    # ── Macro 2 ──────────────────────────────────────────────────────────────
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="Una foto de tu plato no sabe lo que comes. Pero el algoritmo te convence de que sí — y le crees más que a tu cuerpo.",
         fenomeno="Las apps de conteo calórico pasaron de herramienta a obsesión. El algoritmo que 'te ayuda a comer mejor' se convierte en la voz que condena cada nutriente. El número en pantalla pesa más que la saciedad.",
         hashtags="#AppQueEnfermó · #MyFitnessPalToxic · #AlgoritmoDeMiDieta",
         triggers=[
             dict(stat="180M",  desc="Usuarios MyFitnessPal; 75% de pacientes con trastorno alimentario la usaba.", source="GripRoom / PMC NLM · 2026"),
             dict(stat="73%",   desc="De pacientes con trastorno creyó que la app contribuyó al desarrollo del mismo.", source="GripRoom / PMC NLM · 2026"),
             dict(stat="IA",    desc="Apps con reconocimiento por foto funcionan como 'gateway' a trastorno en perfeccionistas.", source="Sage Journals / Ohio State · 2024-2026"),
         ],
         signals=[
             dict(png="macro-2-1-myfitnesspal-app-ui.png",
                  caption="MyFitnessPal UI — 976 cal + macro breakdown. 'Nutrition tracking for real life'.",
                  source="MyFitnessPal · 2026",
                  url="https://www.myfitnesspal.com"),
             dict(png="macro-2-1-flinders-fitnessapp-disorder.png",
                  caption="Fitness apps fuelling disordered eating — Flinders University 2025.",
                  source="Flinders University · Feb 2025",
                  url="https://news.flinders.edu.au/blog/2025/02/22/fitness-apps-fuelling-disordered-eating/"),
             dict(png="macro-2-2-cropink-social-food-stats.png",
                  caption="74% usa redes para decidir qué comer — el feed como primer nutricionista.",
                  source="Cropink · 2026",
                  url="https://cropink.com/restaurant-social-media-statistics"),
         ]),
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="Antes mamá decidía qué había de comer. Hoy lo decide el For You Page — y te vende los ingredientes en el mismo scroll.",
         fenomeno="El joven dominicano abre TikTok antes de abrir el refrigerador. Las recetas virales compiten con la tradición oral heredada — y en muchos hogares jóvenes el algoritmo está ganando.",
         hashtags="#TikTokRecetas · #ForYouPageDeCocina · #AlgoritmoDeAlmuerzo",
         triggers=[
             dict(stat="42",       desc="Índice de contenido food en TikTok enero 2026 — la plataforma como primer recetario.", source="Accio / TikTok Food Trends · 2026"),
             dict(stat="US$759M",  desc="GMV de food en TikTok Shop 2025 — integración receta → carrito en plataforma.", source="Capital One Shopping · 2025"),
             dict(stat="2×",       desc="Las marcas grandes casi duplicaron ventas en TikTok Shop en 2025.", source="Modern Retail · 2025"),
         ],
         signals=[
             dict(png="macro-2-2-tiktokshop-food-gmv.png",
                  caption="TikTok Shop: food = 13.6% del GMV total 2025. El supermercado vive dentro del feed.",
                  source="Resourcera · 2026",
                  url="https://resourcera.com/data/social/tiktok-shop-statistics/"),
             dict(png="macro-2-2-modernretail-tiktokshop-brands.png",
                  caption="Modern Retail: ventas de marcas grandes casi duplicaron en TikTok Shop 2025.",
                  source="Modern Retail · 2025",
                  url="https://www.modernretail.co/technology/sales-from-major-brands-on-tiktok-shop-nearly-doubled-in-2025-drawing-ulta-and-sally-beauty/"),
             dict(png="macro-2-2-cropink-social-food-stats.png",
                  caption="74% usa redes para decidir qué comer; 50% reporta influencia directa.",
                  source="Cropink · 2026",
                  url="https://cropink.com/restaurant-social-media-statistics"),
         ]),
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="El truco de poner un video para que el niño coma se volvió condición — el iPad es la única forma de que el plato baje.",
         fenomeno="El niño no come sin el iPad. El joven de 18 no cena sin Netflix. La pantalla dejó de ser acompañamiento y se volvió condición. La mesa familiar tiene un competidor que casi siempre gana.",
         hashtags="#iPadKid · #PantallaMientrasCome · #NetflixYCena",
         triggers=[
             dict(stat="40%",    desc="De niños tiene iPad a los 2 años; 2.6 hrs/día promedio; solo 1% cumple límites recomendados.", source="Common Sense Media · 2025"),
             dict(stat="2 años", desc="Edad a la que 4 de cada 10 niños ya tiene tablet según Census 2025 de Common Sense Media.", source="K12 Dive / CSM · 2025"),
             dict(stat="17%",    desc="De familias dominicanas no comparte las horas de comida — y donde sí, la pantalla se sentó primero.", source="Código Casa · 2025"),
         ],
         signals=[
             dict(png="macro-2-3-tiktok-ipadkid-debate.png",
                  caption="TikTok debate viral: 'Kids and iPads at the table… yes or no?' — pantallas en la mesa.",
                  source="TikTok @sextedmyboss · 2025",
                  url="https://www.tiktok.com/@sextedmyboss/video/7475054384771075350"),
             dict(png="macro-2-3-k12dive-csm-screentimekids.png",
                  caption="'Half of young children own a cell phone or tablet' — foto editorial niño con tablet.",
                  source="K12 Dive / Common Sense Media · 2025",
                  url="https://www.k12dive.com/news/half-of-young-children-own-a-cell-phone-or-tablet/741318/"),
             dict(png="macro-2-3-newsmedical-screentime-proxy.png",
                  caption="GLP-1 altera apetito y comportamiento — proxy de la pantalla como mediador del comer.",
                  source="News Medical · 2026",
                  url="https://www.news-medical.net/health/How-GLP-1-Weight-Loss-Drugs-Affect-Appetite-Mood-and-Behavior.aspx"),
         ]),
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="El consumidor sano se pega un sensor de glucosa y descubre que la uva le sube más el azúcar que el helado.",
         fenomeno="Los wearables de glucosa OTC (Lingo, Stelo) salieron del nicho diabético y entraron al consumer health. El 'comer bien' dejó de ser opinión — ahora es métrica continua.",
         hashtags="#LingoRD · #SensorDeGlucosa · #ComerConDato",
         triggers=[
             dict(stat="US$80B",  desc="Mercado de wearables y health tracking en 2024; proyecta US$200B+ para 2030.", source="Statista · 2025"),
             dict(stat="14 días", desc="Abbott Lingo — CGM sin prescripción, biosensor de 14 días en Walmart y Amazon.", source="Abbott Newsroom · 2025"),
             dict(stat="OTC",     desc="FDA aprobó primeros CGMs OTC en 2024; expansión al consumidor no-diabético.", source="Scripps News · 2025"),
         ],
         signals=[
             dict(png="macro-2-4-hellolingo-cgm-hero.png",
                  caption="Abbott Lingo hero — mujer con sensor en brazo: 'My glucose, my insights'. CGM OTC.",
                  source="Abbott Lingo · 2025",
                  url="https://www.hellolingo.com"),
             dict(png="macro-2-4-scripps-cgm-sensor-arm.png",
                  caption="Foto AP: brazo con sensor de glucosa — 'CGMs in vogue' para consumidor no-diabético.",
                  source="Scripps News / AP · 2025",
                  url="https://www.scrippsnews.com/health/continuous-glucose-monitors-are-in-vogue-but-do-you-really-need-to-track-your-blood-sugar"),
             dict(png="macro-2-0-resourcera-tiktokshop-gmv.png",
                  caption="TikTok Shop Key Insights 2026: GMV US$64.3B — el contexto tech que rodea al wearable.",
                  source="Resourcera · 2026",
                  url="https://resourcera.com/data/social/tiktok-shop-statistics/"),
         ]),
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="Una creadora cocina en vivo, te muestra el producto, lo agregas al carrito sin salir del feed. El súper se volvió streaming.",
         fenomeno="Live shopping pasó del nicho beauty al supermercado: snacks, salsas, kits de receta vendidos durante el video. Food es 13.6% del GMV de TikTok Shop. El próximo carrito será un live stream.",
         hashtags="#TikTokShopFood · #CocinaEnVivo · #CarritoDelFeed",
         triggers=[
             dict(stat="US$64B", desc="GMV total TikTok Shop 2025; food = 13.6% = US$759.84M; ticket food US$43.20.", source="Capital One Shopping / Resourcera · 2025-2026"),
             dict(stat="+84%",   desc="Live shopping creció 84% YoY en 2025; conversión live 6.1% vs feed 4.7%.", source="Resourcera · 2026"),
             dict(stat="1er",    desc="Primer supermercado 100% online abre en Santo Domingo — grocery digital prepara terreno.", source="St Kitts Nevis Observer · 2025"),
         ],
         signals=[
             dict(png="macro-2-5-modernretail-tiktokshop-2025.png",
                  caption="Modern Retail: TikTok Shop 2025 — marcas grandes duplicaron ventas; food como categoría #1.",
                  source="Modern Retail · 2025",
                  url="https://www.modernretail.co/technology/sales-from-major-brands-on-tiktok-shop-nearly-doubled-in-2025-drawing-ulta-and-sally-beauty/"),
             dict(png="macro-2-5-resourcera-tiktokshop-stats.png",
                  caption="Resourcera: GMV US$64.3B + ticket food US$43.20 + live shopping +84% YoY.",
                  source="Resourcera · 2026",
                  url="https://resourcera.com/data/social/tiktok-shop-statistics/"),
             dict(png="macro-1-5-stkitts-online-super-sd.png",
                  caption="Primer súper 100% online en Santo Domingo — la grocería dominicana migra a app.",
                  source="St Kitts Nevis Observer · 2025",
                  url="https://www.thestkittsnevisobserver.com/first-online-only-supermarket-opens-in-santo-domingo/"),
         ]),
    # ── Macro 3 ──────────────────────────────────────────────────────────────
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="Ver lo que otros comen se volvió uno de los formatos más consumidos de internet. Ya no es comida — es identidad.",
         fenomeno="'What I Eat in a Day' explota no por curiosidad culinaria — por validación. Ver lo que come otro para confirmar, comparar o inspirarse. El plato ajeno es espejo. Y juez.",
         hashtags="#QuéComoEnUnDía · #WhatIEatInADay · #AlimentaciónEnPantalla",
         triggers=[
             dict(stat="74%",  desc="De personas usa redes para decidir qué/dónde comer; 50% reporta influencia directa.", source="Cropink · 2026"),
             dict(stat="Top",  desc="'What I Eat in a Day' entre top food trends 2026; engagement que el algoritmo premia.", source="Chowhound / TikTok Trends · 2026"),
             dict(stat="2026", desc="Whole Foods predice bowl colorido como 'comer bien aspiracional' que WIEIAD replica.", source="VegNews · 2025"),
         ],
         signals=[
             dict(png="macro-3-1-tiktok-wieiad-hanfoodfit.png",
                  caption="@hanfoodfit — 'What I eat in a day, healthy and balanced' aspiracional #8020rule.",
                  source="TikTok @hanfoodfit · 2025",
                  url="https://www.tiktok.com/@hanfoodfit/video/7493474947029880086"),
             dict(png="macro-3-1-vegnews-food-trend-hero.png",
                  caption="Bowl proteína + grains + vegetales coloridos — 'comer bien aspiracional 2026' que WIEIAD replica.",
                  source="VegNews · 2025",
                  url="https://vegnews.com/fiber-whole-foods-2026-top-trend"),
             dict(png="macro-3-1-cropink-social-food-decisions.png",
                  caption="Cropink: 74% usa redes para decidir qué comer; el feed como nutricionista.",
                  source="Cropink · 2026",
                  url="https://cropink.com/restaurant-social-media-statistics"),
         ]),
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="El mukbang nació porque hay gente que come sola y prefiere ver a alguien comer antes que comer en silencio.",
         fenomeno="Nació en Corea como compañía virtual. Hoy es negocio millonario. El dominicano lo consume porque la mesa vacía duele — y una pantalla llena el silencio del comedor.",
         hashtags="#MukbangLatino · #ComerSoloPeroNoTanto · #SoledadEnLaMesa",
         triggers=[
             dict(stat="5.3M",  desc="#mukbang supera 5.3M videos en 2025; top creadores ganan hasta US$10K/mes.", source="Distraction Magazine / PMC · 2025"),
             dict(stat="68.5%", desc="De jóvenes universitarias ve videos de comida regularmente — vínculo parasocial como consuelo.", source="Western Gazette / PMC · 2025-2026"),
             dict(stat="2B+",   desc="Nickocado Avocado supera 2B views en YouTube — el mukbang como negocio millonario.", source="PMC · 2025"),
         ],
         signals=[
             dict(png="macro-3-2-youtube-mukbang-search-grid.png",
                  caption="Grid YouTube 'mukbang' — thumbnails comida extrema + ASMR con millones de vistas.",
                  source="YouTube · 2026",
                  url="https://www.youtube.com/results?search_query=mukbang"),
             dict(png="macro-3-1-tiktok-wieiad-hanfoodfit.png",
                  caption="@hanfoodfit — formato WIEIAD como compañía parasocial; el comer-en-pantalla.",
                  source="TikTok @hanfoodfit · 2025",
                  url="https://www.tiktok.com/@hanfoodfit/video/7493474947029880086"),
             dict(png="macro-3-3-newsmedical-cooking-proxy.png",
                  caption="Medicalización del hambre — GLP-1 crea contrapunto; el mukbang es el polo opuesto analógico.",
                  source="News Medical · 2026",
                  url="https://www.news-medical.net/health/How-GLP-1-Weight-Loss-Drugs-Affect-Appetite-Mood-and-Behavior.aspx"),
         ]),
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="Cuando todo lo demás está fuera de control, la cocina es el único sitio donde lo que hago sí sale como quiero.",
         fenomeno="Bajo burnout y presión social, adultos jóvenes descubrieron que cocinar y hornear son terapia real. No es hobbyismo — es el único espacio donde lo que controlas eres tú.",
         hashtags="#CocinaComoTerapia · #HornearParaDesestresarse · #LoveLanguageCocina",
         triggers=[
             dict(stat="↓",     desc="Hornear activa rutas de dopamina y reduce cortisol — equivalente a mindfulness clínico según Kaiser Permanente.", source="Kaiser Permanente / NeuroLaunch · 2025-2026"),
             dict(stat="2026",  desc="Ola de cancelaciones de delivery + vuelta a la cocina como anti-ansiedad digital.", source="EditorialGe / Cooking as Therapy · 2026"),
             dict(stat="GLP-1", desc="Medicalización del hambre (Ozempic) crea contrapunto cultural: la cocina como ritual analógico.", source="News Medical · 2026"),
         ],
         signals=[
             dict(png="macro-3-3-tiktok-natalie-stressbaking.png",
                  caption="@chef_natalie_ — 'stress baking is my form of therapy' #bakingtherapy #bakingtiktok.",
                  source="TikTok @chef_natalie_ · 2025",
                  url="https://www.tiktok.com/@chef_natalie_/video/7569545767090703647"),
             dict(png="macro-3-3-newsmedical-cooking-proxy.png",
                  caption="Jeringa semaglutide — GLP-1 altera apetito; la cocina como contrapunto analógico a la farmacología.",
                  source="News Medical · 2026",
                  url="https://www.news-medical.net/health/How-GLP-1-Weight-Loss-Drugs-Affect-Appetite-Mood-and-Behavior.aspx"),
             dict(png="macro-3-1-vegnews-food-trend-hero.png",
                  caption="Bowl aspiracional 2026 — cocinar para el feed y para el alma; el plato que también es estética.",
                  source="VegNews · 2025",
                  url="https://vegnews.com/fiber-whole-foods-2026-top-trend"),
         ]),
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="El FOMO de bajar de peso llegó a su versión más extrema: eliminar todo lo que no sea animal. La sangre cuenta otra historia.",
         fenomeno="Joe Rogan lo popularizó, los influencers lo viralizaron. Solo carne, mantequilla y huevo. El algoritmo lo distribuye más rápido que la evidencia clínica que lo contradice.",
         hashtags="#DietaCarnívora · #FOMODeBajarDePeso · #CarnivoreVsColesterol",
         triggers=[
             dict(stat="2.6M",   desc="#carnivore supera 2.6M publicaciones en Instagram a noviembre 2025.", source="ResearchGate / Fox News · 2025-2026"),
             dict(stat="+36",    desc="LDL promedio sube de 126 a 172 mg/dL; un caso documentado pasó de 163 a 365.", source="Nutrients Journal · Ene 2026"),
             dict(stat="2026",   desc="Whole Foods predice 'Year of the Fiber' + flexitarian — mainstream pivota mientras carnivore escala.", source="Whole Foods / VegNews · 2026"),
         ],
         signals=[
             dict(png="macro-3-4-tiktok-carnivore-steakbuttergal.png",
                  caption="@Steakandbuttergal — #carnivorediet: la creadora más viral de solo carne + mantequilla + huevos.",
                  source="TikTok @steakandbuttergal · 2025",
                  url="https://www.tiktok.com/@steakandbuttergal/video/7577437952679087374"),
             dict(png="macro-3-4-vegnews-protein-fiber-trend.png",
                  caption="Bowl colorido aspiracional 2026 — pivot mainstream de proteína → fibra mientras carnivore escala.",
                  source="VegNews · 2025",
                  url="https://vegnews.com/fiber-whole-foods-2026-top-trend"),
             dict(png="macro-3-0-vegnews-wholefoods-fiber-2026.png",
                  caption="'Move Over Protein' — Whole Foods predice Año de la Fibra 2026 como contratendencia.",
                  source="VegNews · Oct 2025",
                  url="https://vegnews.com/fiber-whole-foods-2026-top-trend"),
         ]),
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="GLP-1 silencia el 'food noise' del cerebro. La nueva conversación no es qué cocinar — es si lo deseo o solo me acordé que existía.",
         fenomeno="Ozempic y Mounjaro reescriben la relación con la comida: ya no se trata de fuerza de voluntad — se trata de farmacología que apaga el ruido mental. El feed normaliza la conversación.",
         hashtags="#FoodNoise · #OzempicDiary · #GLP1RD",
         triggers=[
             dict(stat="58%",   desc="Siente menos hambre con GLP-1; 64% se llena antes; 21-23% reporta cambios de sabor.", source="EASD 2025 / News-Medical · 2025"),
             dict(stat="n=411", desc="Survey EASD Annual Meeting 2025 sobre impacto cognitivo del GLP-1 en el food noise.", source="EASD 2025"),
             dict(stat="🧠",    desc="Scientific American + Medscape documentan cómo GLP-1 reduce respuesta cerebral a comida.", source="Scientific American / Medscape · 2025"),
         ],
         signals=[
             dict(png="macro-3-5-sciam-ozempic-food-noise.png",
                  caption="SciAm: ilustración surrealista — cabeza clásica con comida girando. 'Ozempic Quiets Food Noise'.",
                  source="Scientific American · Jun 2024",
                  url="https://www.scientificamerican.com/article/ozempic-quiets-food-noise-in-the-brain-but-how/"),
             dict(png="macro-3-5-newsmedical-glp1-appetite.png",
                  caption="Jeringa semaglutide — 58% siente menos hambre con GLP-1; 64% se llena antes (EASD 2025).",
                  source="News Medical · 2026",
                  url="https://www.news-medical.net/health/How-GLP-1-Weight-Loss-Drugs-Affect-Appetite-Mood-and-Behavior.aspx"),
             dict(png="macro-3-5-tiktok-glp1-foodnoise.png",
                  caption="@JanelleRohner — responde sobre GLP-1 y food noise; #glp1community decenas de millones de views.",
                  source="TikTok @janellerohner · 2025",
                  url="https://www.tiktok.com/@janellerohner/video/7564545141835418911"),
         ]),
]

if __name__ == "__main__":
    build_deck(DIVIDERS, MICROS, SCREENSHOTS, OUTPUT)
