"""
build_trends_educacion.py — Capítulo EDUCACIÓN

SOLO DATOS. Todo el layout vive en trends_deck_engine.py (el "CSS" central).
Para cambiar espaciado/tamaños/fuentes NO toques este archivo — edita el motor
y TODOS los capítulos se actualizan idénticos.

Data corregida post-auditoría 2026-06-10:
- Micro 2.5: ancla cambiada de "98% no usa IA" a EDUCA ">90% docentes RD".
- Triggers reatribuidos: College Board, Grand View, Mordor, HEPI, Rival IQ, SHRM,
  Computerworld, EDUCA, WEF, JHU, RAND, edX, Duolingo SEC, Coursera, Khan Academy.
- Fuentes viejas eliminadas: Demandsage, FMI como ancla, stat 98% sin respaldo.
- Fenomeno bodies ajustados para caber en col-left (motor col-left es flow dinámico,
  los cuerpos de texto largos se recortaron al mínimo semántico necesario).
"""

from pathlib import Path
from trends_deck_engine import build_deck

BASE        = Path("/Users/jeremyrodriguez/Documents/Cerebro/Código Casa/Team Trends CC")
SCREENSHOTS = BASE / "screenshots" / "trends-educacion"
OUTPUT      = BASE / "outputs" / "trends-educacion-forecast.pptx"

# ─── Macros ─────────────────────────────────────────────────────────────────
M1_N = "MACRO 1"; M1_NAME = "INVENTOLOGÍA DE LA ADULTEZ"
M1_TAG = "Un mundo en crisis está reescribiendo qué significa ser adulto y formar familia."
M2_N = "MACRO 2"; M2_NAME = "LOS HERNÁNDEZ ARE PROMPTED"
M2_TAG = "El dominicano ya entró al mundo prompteado. Solo no lo nombra así."
M3_N = "MACRO 3"; M3_NAME = "ALGORITMO DEL HOGAR"
M3_TAG = "El feed se sentó en la mesa y nadie le ofreció silla."

DIVIDERS = [
    (1, M1_NAME, M1_TAG),
    (2, M2_NAME, M2_TAG),
    (3, M3_NAME, M3_TAG),
]

MICROS = [
    # ── Macro 1 ──────────────────────────────────────────────────────────────
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="El diploma dejó de ser el ticket: 53% de empleadores ya contrata por skills demostrados, y la generación que entra al mercado lo sabe antes de matricularse.",
         fenomeno="Por décadas el título universitario fue la prueba de que servías para el trabajo. Eso se aflojó. En 2025, 53% de empleadores dejó de pedir título y empezó a contratar por habilidad demostrada — subió desde 30% el año anterior. Pero el discurso va más rápido que la práctica: 85% dice contratar por skills, y en los números reales apenas 1 de cada 700 contrataciones ocurre sin título.",
         hashtags="#skillsnotdegrees · #collegedropout · #selftaught · #careerchange · #notitulonecesario",
         triggers=[
             dict(stat="53%",     desc="De empleadores eliminó el requisito de título en 2025 (subió desde 30% el año anterior).", source="TestGorilla · 2025"),
             dict(stat="85%",     desc="Dice contratar por skills, pero solo 1 de cada 700 contrataciones reales es sin título. La paradoja del trend.", source="Harvard / Burning Glass · The Interview Guys · 2025"),
             dict(stat="#skills", desc="#skillsoverdegrees y testimonios de college dropout acumulan decenas de millones de views.", source="TikTok Discover · 2025"),
         ],
         signals=[
             dict(png="macro-1-1-tiktok-skillsnotdegrees.png",
                  caption="Grid del hashtag #skillsnotdegrees en TikTok — skills vs título, la paradoja en el feed.",
                  source="TikTok Discover · 2025",
                  url="https://www.tiktok.com/tag/skillsnotdegrees"),
             dict(png="macro-1-1-interviewguys-skills-hiring-2025.png",
                  caption="State of Skills-Based Hiring 2025: la paradoja 85% dice skills vs 1/700 contrataciones reales.",
                  source="The Interview Guys · 2025",
                  url="https://blog.theinterviewguys.com/the-state-of-skills-based-hiring/"),
             dict(png="macro-1-0-accelerec-skills-hiring.png",
                  caption="'The 4-Year Degree Is Dead' — skills-based hiring como el nuevo default en contratación.",
                  source="Accelerec · 2025",
                  url="https://accelerec.com/the-4-year-degree-is-dead-why-skills-based-hiring-is-taking-over-in-2025/"),
         ]),
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="Ya nadie 'terminó de estudiar': el adulto LATAM se re-skillea cada 2-3 años porque 39% de las habilidades laborales cambia para 2030.",
         fenomeno="Antes te graduabas y cerrabas el capítulo de estudiar. Ese capítulo no cierra ya. 70% de profesionales dice que el upskilling es clave para su seguridad laboral, y 72% de los managers ya está haciendo upskilling. El driver: 39% de las habilidades del trabajo van a cambiar para 2030. Quedarte quieto es quedarte atrás.",
         hashtags="#lifelonglearning · #reskilling · #upskilling · #aprenderparasiempre · #careergrowth",
         triggers=[
             dict(stat="70%",     desc="Dice que el upskilling es clave para su seguridad laboral; 72% de managers ya hace upskilling.", source="edX Spring · 2025"),
             dict(stat="129%",    desc="Crecimiento interanual de inscripciones LATAM en ciberseguridad en Coursera.", source="Coursera Global Skills Report · 2025"),
             dict(stat="39%",     desc="De las habilidades laborales cambiarán para 2030 — el 'Great Skills Reset' del WEF.", source="WEF Future of Jobs · 2025"),
         ],
         signals=[
             dict(png="macro-1-2-coursera-global-skills-report.png",
                  caption="Coursera Global Skills Report — upskilling LATAM en números, ciberseguridad +129% interanual.",
                  source="Coursera · 2025",
                  url="https://www.coursera.org/skills-reports/global"),
             dict(png="macro-1-2-wef-future-of-jobs.png",
                  caption="WEF Future of Jobs 2025: 39% de skills cambian para 2030 — el 'Great Skills Reset'.",
                  source="WEF Future of Jobs · 2025",
                  url="https://www.weforum.org/stories/2025/01/future-of-jobs-report-2025-jobs-of-the-future-and-the-skills-you-need-to-get-them/"),
             dict(png="macro-1-2-coursera-global-skills-report.png",
                  caption="Coursera como producto del lifelong learning — el reporte de skills como espejo del mercado.",
                  source="Coursera · 2025",
                  url="https://www.coursera.org/skills-reports/global"),
         ]),
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="Familias globales sacan a sus hijos del colegio por elección, no por crisis: el aula de 30 compite con microschools de 5-15 y currículos a la medida.",
         fenomeno="El homeschool dejó de ser cosa de nicho. Creció 4.9% en 2024-25, casi 3x la tasa pre-pandemia. En paralelo aparecen las microschools — hubs de 5 a 15 alumnos donde la familia diseña el currículo. Entre 1 y 2 millones asisten full-time. La motivación: control. La familia quiere armar la educación, no delegarla.",
         hashtags="#homeschool · #microschool · #unschooling · #homeschoollife · #educacionalternativa",
         triggers=[
             dict(stat="4.9%",    desc="Crecimiento del homeschool en 2024-25, casi 3x la tasa pre-pandemia; 36% de estados con máximos históricos.", source="JHU Institute for Education Policy · 2025"),
             dict(stat="1-2M",    desc="Estudiantes en EEUU ya asisten a microschools full-time, promedio 22 alumnos por hub.", source="RAND / National Microschooling Center · 2025"),
             dict(stat="22",      desc="Alumnos promedio por microschool — grupos pequeños donde la familia diseña el currículo.", source="CBS Miami · 2025"),
         ],
         signals=[
             dict(png="macro-1-3-cbsmiami-microschools.png",
                  caption="CBS Miami: hub de aprendizaje alternativo en Florida — 'Microschools on the rise'.",
                  source="CBS Miami · 2025",
                  url="https://www.cbsnews.com/miami/news/microschools-families-flexible-alternative/"),
             dict(png="macro-1-3-jhu-homeschool-growth.png",
                  caption="JHU Institute for Education Policy — crecimiento 4.9% con mapa de estados en máximos históricos.",
                  source="JHU Institute for Education Policy · 2025",
                  url="https://education.jhu.edu/edpolicy/policy-research-initiatives/homeschool-hub/homeschool-growth-2024-2025/"),
             dict(png="macro-1-3-theschoolhouse-microschools.png",
                  caption="'Why Microschools Are Rising' — el grupo pequeño como modelo pedagógico de la familia activa.",
                  source="The School House · 2025",
                  url="https://www.theschoolhouse.org/post/rising-microschools-education"),
         ]),
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="El 'siguiente paso obvio' tras el bachillerato dejó de ser obvio: gap year, bootcamp y emprendimiento adolescente sustituyen el ingreso inmediato a la universidad.",
         fenomeno="Solo 18% de Gen Z ve escalar la escalera corporativa como algo inteligente. Y Big Tech lo validó: Google, IBM y Tesla quitaron el título para muchos roles. El recién graduado se da un año, hace un bootcamp, o monta un ingreso con skills digitales antes de comprometerse. No es vagancia. Es calcular el costo antes de firmar.",
         hashtags="#gapyear · #alternativestocollege · #teenentrepreneur · #nocollege · #emprendimientojoven",
         triggers=[
             dict(stat="18%",      desc="De Gen Z global ve subir la escalera corporativa como algo inteligente — el camino lineal perdió prestigio.", source="Fiverr · Oct 2025"),
             dict(stat="#gapyear", desc="#gapyear y los formatos 'alternatives to college' crecen como género propio de contenido.", source="TikTok Discover · 2025"),
             dict(stat="Big Tech", desc="Google, IBM y Tesla eliminaron el título para muchos roles — Computerworld y CNBC lo documentan.", source="Computerworld / CNBC · 2025"),
         ],
         signals=[
             dict(png="macro-1-4-tiktok-gapyear.png",
                  caption="Grid #gapyear en TikTok — jóvenes mostrando el path alternativo post-bachillerato.",
                  source="TikTok Discover · 2025",
                  url="https://www.tiktok.com/tag/gapyear"),
             dict(png="macro-1-4-computerworld-bigtech-skills.png",
                  caption="Computerworld: IT jobs where a degree is no longer required — Big Tech quita el título.",
                  source="Computerworld · 2025",
                  url="https://www.computerworld.com/article/1614212/it-jobs-where-a-degree-is-no-longer-required.html"),
             dict(png="macro-1-4-cnbc-bigtech-skills.png",
                  caption="CNBC: Google, Apple y otras empresas que ya no requieren título universitario.",
                  source="CNBC · 2024",
                  url="https://www.cnbc.com/2024/04/09/google-apple-and-other-companies-that-no-longer-require-a-college-degree.html"),
         ]),
    dict(macro_n=M1_N, macro_name=M1_NAME,
         headline="La familia compensa lo que la escuela dejó de garantizar: 70% de niños en países de ingreso medio-bajo no lee bien a los 10, y el mercado de tutoría AI ya vale US$3.55B.",
         fenomeno="La pandemia dejó un hueco que el sistema formal no recuperó. La pobreza de aprendizaje subió a ~70% en países de ingreso medio-bajo; LATAM perdió 225 días de clase. NAEP reportó mínimos históricos. La familia pagó el refuerzo por fuera. El mercado de tutoría AI llegó a US$3.55B en 2025.",
         hashtags="#learningloss · #tutoring · #refuerzoescolar · #educationcrisis · #apoyoescolar",
         triggers=[
             dict(stat="~70%",     desc="Pobreza de aprendizaje post-pandemia; LATAM perdió en promedio 225 días de clase presencial.", source="Banco Mundial / UNESCO · 2022"),
             dict(stat="NAEP",     desc="Mínimos históricos en lectura y matemática (serie de evaluación desde 1992) reportados por NAEP.", source="NAEP / UNA-USA · 2024"),
             dict(stat="US$3.55B", desc="Mercado de tutoría AI en 2025 — la casa suple lo que el aula dejó de asegurar.", source="Mordor Intelligence · 2025"),
         ],
         signals=[
             dict(png="macro-1-5-worldbank-learning-poverty.png",
                  caption="Banco Mundial: mapa de learning poverty global — ~70% en países de ingreso medio-bajo post-pandemia.",
                  source="Banco Mundial / UNESCO · 2022",
                  url="https://www.worldbank.org/en/topic/education/publication/state-of-global-learning-poverty"),
             dict(png="macro-1-5-unausa-naep-scores.png",
                  caption="NAEP vía UNA-USA: mínimos históricos en lectura y matemática — la serie desde 1992.",
                  source="NAEP / UNA-USA · 2024",
                  url="https://unausa.org/gga-blog-post-1/"),
             dict(png="macro-1-5-worldbank-learning-poverty.png",
                  caption="World Bank: la pobreza de aprendizaje como dato global que empuja el mercado de tutoría AI.",
                  source="Banco Mundial · 2022",
                  url="https://www.worldbank.org/en/topic/education/publication/state-of-global-learning-poverty"),
         ]),
    # ── Macro 2 ──────────────────────────────────────────────────────────────
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="El tutor 1-a-1 dejó de ser privilegio de élite: Khanmigo pasó de 68k a 700k usuarios y la familia accede a tutoría con IA por una fracción del costo del profesor particular.",
         fenomeno="La tutoría privada siempre fue cosa de quien podía pagarla. Eso se está moviendo. Khanmigo pasó de 68k a 700k estudiantes en un ciclo; Sal Khan citó 1.4M acumulado a mediados de 2025. El mercado de tutores AI va de US$3.55B a US$6.45B para 2030. El estudiante resuelve dudas a cualquier hora con un tutor que no se cansa ni cobra por sesión.",
         hashtags="#aitutor · #khanmigo · #studywithai · #tutoriaIA · #aprenderconIA",
         triggers=[
             dict(stat="700k",     desc="Usuarios de Khanmigo en un ciclo (creció desde 68k); Sal Khan citó 1.4M acumulado a mediados 2025.", source="Khan Academy / GlobalSociety · 2025"),
             dict(stat="US$3.55B", desc="Mercado de tutores AI en 2025, proyectado a US$6.45B en 2030.", source="Mordor Intelligence · 2025"),
             dict(stat="StudyTok", desc="Demos de 'AI tutor' y 'how I use AI to study' virales en StudyTok.", source="TikTok Discover · 2025"),
         ],
         signals=[
             dict(png="macro-3-0-tiktok-studytok-tag.png",
                  caption="TikTok StudyTok: 'AI helped me pass', testimonios de estudio con IA en el feed.",
                  source="TikTok Discover · 2025",
                  url="https://www.tiktok.com/tag/studytok"),
             dict(png="macro-2-1-globalsociety-khanmigo-ai-tools.png",
                  caption="GlobalSociety: Khanmigo escala de 68k a 700k en distritos escolares con herramientas docentes AI.",
                  source="GlobalSociety · 2025",
                  url="https://www.globalsociety.earth/post/khan-academy-rolls-out-ai-powered-teaching-tools-as-school-districts-scale-up-adoption"),
             dict(png="macro-2-1-khanmigo-hero-landing.png",
                  caption="Khanmigo UI — tutor AI siempre disponible, acceso 24/7 por fracción del costo del particular.",
                  source="Khanmigo · 2025",
                  url="https://khanmigo.ai/"),
         ]),
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="Aprender se gamificó y compite con TikTok usando las mismas mecánicas: Duolingo sostiene 50.5M usuarios diarios con rachas, ligas y la culpa del búho.",
         fenomeno="El estudio nunca tuvo dopamina. Duolingo se la puso. Superó 50.5M usuarios diarios en Q3 2025 (+36% interanual). Rachas, ligas, notificaciones — las mismas mecánicas de enganche que usa TikTok, aplicadas a aprender un idioma. Revenue Q3: US$271.7M (+41%), 11.5M suscriptores pagos. La gente mantiene rachas no por disciplina — por el miedo a romperla.",
         hashtags="#duolingo · #duostreak · #languagelearning · #gamifiedlearning · #aprenderjugando",
         triggers=[
             dict(stat="50.5M",   desc="Usuarios diarios de Duolingo en Q3 2025 (+36% interanual) — las mecánicas de juego sostienen el hábito.", source="Duolingo 8-K SEC · 2025"),
             dict(stat="US$271M", desc="Revenue Q3 2025 (+41%); 11.5M suscriptores pagos — gamificación que convierte.", source="Duolingo SEC Filing FY2025"),
             dict(stat="Duo",     desc="El búho Duo y la 'Duolingo guilt' son un género viral con cientos de millones de views.", source="TikTok · 2025"),
         ],
         signals=[
             dict(png="macro-2-2-duolingo-landing.png",
                  caption="Duolingo landing: el búho Duo, aprender 5 minutos al día con mecánicas de streak.",
                  source="Duolingo · 2025",
                  url="https://www.duolingo.com/"),
             dict(png="macro-2-2-duolingo-streaks-gamification.png",
                  caption="Análisis de rachas y retención Duolingo — mecánica de streak que sostiene 50.5M DAU.",
                  source="Strivecloud · 2025",
                  url="https://www.strivecloud.io/blog/gamification-examples-boost-user-retention-duolingo"),
             dict(png="macro-2-2-strivecloud-duolingo-hero.png",
                  caption="Strivecloud hero: análisis completo de la gamificación de Duolingo — ligas, streaks, leaderboards.",
                  source="Strivecloud · 2025",
                  url="https://www.strivecloud.io/blog/gamification-examples-boost-user-retention-duolingo"),
         ]),
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="La IA generativa automatizó la tarea escolar: 84% de secundaria la usa y entre universitarios 89% la usa para tareas; la pregunta dejó de ser si copian — es si el aprendizaje sobrevive.",
         fenomeno="84% de secundaria usa IA para schoolwork; 89% de universitarios para tareas. En UK saltó de 66% a 92% en un año. El estudiante genera el ensayo con ChatGPT y lo humaniza para esquivar detectores. La pregunta: qué queda del aprendizaje.",
         hashtags="#chatgptforschool · #aihomework · #studyhack · #aidetector · #tareaconIA",
         triggers=[
             dict(stat="84%",  desc="De estudiantes de secundaria usa IA generativa para schoolwork.", source="College Board · 2025"),
             dict(stat="89%",  desc="De universitarios que usan IA la aplica para tareas; 53% para ensayos.", source="Nerdynav · 2025"),
             dict(stat="92%",  desc="De universitarios UK usa IA en 2025 (saltó de 66% en 2024 a 92% en 2025).", source="HEPI · 2025"),
         ],
         signals=[
             dict(png="macro-2-3-nerdynav-chatgpt-cheating-infographic.png",
                  caption="Nerdynav: 'humanize AI text' — el tutorial para esquivar detectores, uso de IA por tipo de tarea.",
                  source="Nerdynav · 2025",
                  url="https://nerdynav.com/chatgpt-cheating-statistics/"),
             dict(png="macro-2-3-hepi-ai-students.png",
                  caption="HEPI: uso de IA entre universitarios UK sube a 92% en 2025 — el estudio que ancla el dato.",
                  source="HEPI · 2025",
                  url="https://www.hepi.ac.uk/2025/02/26/student-generative-ai-survey-2025/"),
             dict(png="macro-2-3-nerdynav-student-usage-chart.png",
                  caption="Chart de uso de IA por tipo de tarea — 89% tareas, 53% ensayos, 84% secundaria.",
                  source="Nerdynav · 2025",
                  url="https://nerdynav.com/chatgpt-cheating-statistics/"),
         ]),
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="El diploma de papel se mudó a la nube: 90% de empleadores prefiere candidato con microcredencial, y los badges verificables se volvieron moneda de empleabilidad.",
         fenomeno="El título tardaba 4 años y vivía en una pared. La microcredencial tarda semanas y vive en LinkedIn. Más del 90% de empleadores prefiere candidato con microcredencial. Coursera tiene millones de inscripciones en certificados entry-level. El profesional exhibe el badge de Google como prueba portátil de que sabe hacer algo.",
         hashtags="#microcredentials · #digitalbadges · #googlecertificate · #coursera · #credencialesdigitales",
         triggers=[
             dict(stat=">90%",    desc="De empleadores prefiere candidato con microcredencial en el CV.", source="Coursera / Fortune · 2025"),
             dict(stat="Millones", desc="De inscripciones en certificados profesionales entry-level de Coursera.", source="Coursera Global Skills Report · 2025"),
             dict(stat="Badge",   desc="'How Digital Credentials Can Elevate Existing Programs' — adopción de credenciales verificables.", source="EdSurge · 2024"),
         ],
         signals=[
             dict(png="macro-2-4-coursera-google-cert.png",
                  caption="Google Career Certificates — badges sin título para roles tech, portfolio portátil en LinkedIn.",
                  source="Google / Coursera · 2025",
                  url="https://grow.google/certificates/"),
             dict(png="macro-2-4-fortune-microcredentials.png",
                  caption="Fortune: 'Getting hired in 2026 = microcredentials' — Coursera CEO a Gen Z.",
                  source="Fortune · Dic 2025",
                  url="https://fortune.com/2025/12/28/2026-microcredential-hiring-trend-coursera-greg-hart/"),
             dict(png="macro-2-4-edsurge-digital-credentials.png",
                  caption="EdSurge: credenciales digitales verificables — cómo elevan los programas existentes.",
                  source="EdSurge · 2024",
                  url="https://www.edsurge.com/news/2024-11-22-how-digital-credentials-can-elevate-existing-programs"),
         ]),
    # MICRO 2.5 — CORREGIDO post-auditoría: ancla EDUCA (>90% docentes RD no usa IA)
    dict(macro_n=M2_N, macro_name=M2_NAME,
         headline="Afuera el docente ya delega lo administrativo a la IA; en RD la facultad apenas la toca: más del 90% de los profesores dominicanos todavía no usa IA en su labor.",
         fenomeno="Afuera el docente sobrecargado delega planes de clase, rúbricas y retroalimentación a la IA. Khanmigo se expandió de 45 a más de 380 distritos. Pero en RD la foto es otra: más del 90% de los docentes todavía no usa IA. La brecha del capítulo no es de estudiantes — es de adopción docente.",
         hashtags="#teacherai · #aiforteachers · #docenteIA · #smartclassroom · #edtechRD",
         triggers=[
             dict(stat=">90%",   desc="De los docentes dominicanos aún no usa IA en su labor educativa — el rezago que ancla el capítulo.", source="EDUCA · El Nacional · 2025"),
             dict(stat="380",    desc="Distritos escolares con Khanmigo (creció desde 45) — herramientas docentes AI que la facultad RD no usa aún.", source="Khan Academy · 2025"),
             dict(stat="SciELO", desc="'Educación Superior en la Era de la IA: Entre la Innovación y la Ética' — paper dominicano sobre adopción docente.", source="SciELO Dominican Republic · 2025"),
         ],
         signals=[
             dict(png="macro-2-5-tiktok-aiforteachers.png",
                  caption="TikTok #aiforteachers: 'teacher hacks con ChatGPT' — herramientas docentes que la facultad RD aún no usa.",
                  source="TikTok Discover · 2025",
                  url="https://www.tiktok.com/tag/aiforteachers"),
             dict(png="macro-2-5-educa-docentes-ia-rd.png",
                  caption="EDUCA / El Nacional: más del 90% de docentes dominicanos no usa IA — el ancla RD del capítulo.",
                  source="EDUCA · El Nacional · 2025",
                  url="https://elnacional.com.do/mas-del-90-de-docentes-dominicanos-no-usa-ia/"),
             dict(png="macro-2-5-scielo-ai-educacion-rd.png",
                  caption="SciELO DO: paper sobre adopción docente IA — doble prueba RD junto al dato EDUCA.",
                  source="SciELO Dominican Republic · 2025",
                  url="https://scielo.do/scielo.php?script=sci_arttext&pid=S2636-21632025003900007&lang=pt"),
         ]),
    # ── Macro 3 ──────────────────────────────────────────────────────────────
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="Estudiar se volvió contenido: 'study with me' lives y notas estéticas convierten el estudio solitario en espectáculo social, con accountability de extraños en el feed.",
         fenomeno="Estudiar era algo que hacías solo en tu cuarto. Ahora se transmite. Los study-with-me lives convirtieron la sesión en experiencia social. El contenido educativo es de las categorías más vistas en TikTok. La disciplina ya no viene de adentro — viene de la mirada de extraños en el feed.",
         hashtags="#studytok · #studywithme · #studygram · #studymotivation · #estudiarconmigo",
         triggers=[
             dict(stat="StudyTok", desc="'Shut up and study' lives y #studytok crecen como subcultura de estudio en comunidad.", source="SmileTutor / TikTok · 2025"),
             dict(stat="Top",      desc="El contenido educativo es una de las categorías más vistas en TikTok.", source="SmileTutor · 2025"),
             dict(stat="Debate",   desc="'The rise of StudyTok: motivational or distraction?' — el estudio performativo en discusión.", source="Southeast Arrow · 2025"),
         ],
         signals=[
             dict(png="macro-3-0-tiktok-studytok-tag.png",
                  caption="Grid #studytok en TikTok — estudio compartido, notas estéticas y accountability del feed.",
                  source="TikTok Discover · 2025",
                  url="https://www.tiktok.com/tag/studytok"),
             dict(png="macro-3-1-youtube-studywithme.png",
                  caption="YouTube 'study with me 2025' — el género expandido a video largo con millones de vistas.",
                  source="YouTube · 2025",
                  url="https://www.youtube.com/results?search_query=study+with+me+2025"),
             dict(png="macro-3-1-southeastarrow-studytok.png",
                  caption="Southeast Arrow: el debate del estudio performativo — motivacional vs distracción.",
                  source="Southeast Arrow · 2025",
                  url="https://www.southeastarrow.com/lifestyle/the-rise-of-studytok-is-it-motivational-or-a-distraction-9240f298"),
         ]),
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="El feed reemplazó al buscador como puerta del conocimiento: 53% de Gen Z consulta TikTok antes que Google, y qué es 'verdad' lo curan creadores, no fuentes.",
         fenomeno="'Búscalo en Google' se volvió 'búscalo en TikTok'. 53% de Gen Z consulta TikTok, Reddit o YouTube antes que Google. El estudiante busca la explicación de un tema en el feed, en formato de 60 segundos con cara y voz. El criterio de qué es verdad ya no lo decide la fuente — lo decide el creador que te cae bien.",
         hashtags="#learnontiktok · #tiktoktaughtme · #edutok · #tiktokitdontgoogleit · #aprendintiktok",
         triggers=[
             dict(stat="53%",   desc="De Gen Z busca en TikTok/Reddit/YouTube antes que Google para informarse.", source="Resolve · 2026"),
             dict(stat="Gen Z", desc="Gen Z y Gen Alpha usan el video social como herramienta de búsqueda cotidiana.", source="Information Matters · 2026"),
             dict(stat="Video", desc="'Why Gen Z turns to YouTube and TikTok for learning' — el video como herramienta educativa.", source="Uqualio · 2025"),
         ],
         signals=[
             dict(png="macro-3-2-informationmatters-genz-tiktok-search.png",
                  caption="Information Matters: 'TikTok It, Don't Google It' — 53% de Gen Z busca en redes sociales primero.",
                  source="Information Matters · 2026",
                  url="https://informationmatters.org/2026/03/tiktok-it-dont-google-it-gen-z-gen-alpha-and-the-rise-of-social-video-as-an-everyday-search-tool/"),
             dict(png="macro-3-2-informationmatters-genz-tiktok-search.png",
                  caption="Resolve: 53% de Gen Z consulta TikTok antes que Google — el buscador perdió su monopolio.",
                  source="Resolve · 2026",
                  url="https://informationmatters.org/2026/03/tiktok-it-dont-google-it-gen-z-gen-alpha-and-the-rise-of-social-video-as-an-everyday-search-tool/"),
             dict(png="macro-3-2-uqualio-genz-video-learning.png",
                  caption="Uqualio: Gen Z y el poder del video en educación — el creador reemplaza a la fuente.",
                  source="Uqualio · 2025",
                  url="https://uqualio.com/post/why-generation-z-turns-to-youtube-and-tiktok-for-learning-the-power-of-video-in-education"),
         ]),
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="El conocimiento se fragmentó al formato del feed: el microlearning en píldoras de 60 segundos reemplaza la clase de 50 minutos, y la escuela K-12 ya está adoptándolo.",
         fenomeno="La clase de 50 minutos perdió contra el tramo de atención que el feed entrenó. El microlearning — conceptos en clips cortos — empezó a reemplazar la lectura larga y la clase entera. Las escuelas K-12 ya están adoptando el formato corto. Una revisión 2025 encontró que el microlearning asistido por TikTok mejora retención y engagement.",
         hashtags="#microlearning · #learnin60seconds · #edutok · #explained · #aprenderrapido",
         triggers=[
             dict(stat="K-12",   desc="'Bringing microlearning to K-12 schools' — las escuelas adoptan el formato corto que el algoritmo impuso.", source="NY State School Boards Assoc. · 2025"),
             dict(stat="2025",   desc="Revisión 2025: microlearning asistido por TikTok mejora retención y engagement en el aula.", source="CTO College · 2026"),
             dict(stat="60 seg", desc="Los formatos 'explained in 60 seconds' dominan EduTok — la píldora de atención del feed.", source="TikTok · 2025"),
         ],
         signals=[
             dict(png="macro-3-3-cto-microlearning.png",
                  caption="CTO College: 'explained in 60 seconds' — el formato del feed que conquista el aula formal.",
                  source="CTO College · 2026",
                  url="https://correctionstocollegeca.org/tiktok-and-the-future-of-learning-microlearning-engagement-and-the-2026-classroom-revolution/"),
             dict(png="macro-3-3-nyssba-microlearning-k12.png",
                  caption="NYSSBA: microlearning entra a K-12 — oportunidades y retos del formato corto en escuelas.",
                  source="NY State School Boards Assoc. · 2025",
                  url="https://www.nyssba.org/news/2025/08/08/on-board-online-august-11-2025/bringing-microlearning-to-k-12-schools-offers-many-opportunities-challenges/"),
             dict(png="macro-3-3-linkedin-learning-ui.png",
                  caption="LinkedIn Learning — cursos bite-sized para profesionales; el microlearning corporativo.",
                  source="LinkedIn Learning · 2025",
                  url="https://www.linkedin.com/learning/"),
         ]),
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="La orientación vocacional migró al feed: creadores muestran 'un día en mi trabajo' y salarios reales, y eso moldea qué carrera elige un adolescente más que cualquier orientador.",
         fenomeno="El orientador escolar tenía un test y un folleto. El feed tiene 'un día en mi vida como [profesión]' y salary reveals. El adolescente descarta o elige una carrera basándose en lo que ve a un creador hacer y ganar. 53% de Gen Z investiga en plataformas sociales antes de tomar decisiones de carrera.",
         hashtags="#careertok · #dayinmylife · #salarytransparency · #careeradvice · #queestudiar",
         triggers=[
             dict(stat="#career", desc="#careertok y 'day in my life as a [profesión]' son formatos masivos que influyen la decisión vocacional.", source="TikTok Discover · 2025"),
             dict(stat="Salary",  desc="'Ultimate list of TikTok trends Gen Z' incluye career/salary transparency como trend 2026.", source="ContentGrip · 2026"),
             dict(stat="53%",     desc="De Gen Z investiga en plataformas sociales antes de tomar decisiones de carrera.", source="Resolve · 2026"),
         ],
         signals=[
             dict(png="macro-3-4-tiktok-careertok.png",
                  caption="Grid #careertok en TikTok — 'day in my life' y salary reveals que moldean la decisión vocacional.",
                  source="TikTok Discover · 2025",
                  url="https://www.tiktok.com/tag/careertok"),
             dict(png="macro-3-4-youtube-careertok.png",
                  caption="YouTube 'day in my life career' — el género vocacional expandido a video largo.",
                  source="YouTube · 2025",
                  url="https://www.youtube.com/results?search_query=day+in+my+life+career+tiktok+2025"),
             dict(png="macro-3-4-contentgrip-tiktok-genz.png",
                  caption="ContentGrip: career/salary transparency en el trend report Gen Z TikTok 2026.",
                  source="ContentGrip · 2026",
                  url="https://www.contentgrip.com/tiktok-trends-gen-z-marketing-guide/"),
         ]),
    dict(macro_n=M3_N, macro_name=M3_NAME,
         headline="El feed materno dicta cómo se educa al niño: MomTok recomienda apps, currículos y 'guilt-free screen time', y desplazó a la maestra como autoridad pedagógica del hogar.",
         fenomeno="La maestra solía ser la autoridad sobre cómo aprende el niño. Ahora compite con otra madre en el feed. MomTok recomienda apps educativas y métodos de crianza, y la madre elige según lo viral. Apps como Kiddopia y Khan Academy Kids se mueven por esa recomendación. La madre confía en otra madre del feed más que en el sistema.",
         hashtags="#momtok · #toddlerlearning · #guiltfreescreentime · #learningapps · #crianzaconpantalla",
         triggers=[
             dict(stat="MomTok",     desc="Apps como Kiddopia ('guilt-free screen time'), SplashLearn y Khan Academy Kids circulan por MomTok.", source="TikTok Discover · 2025"),
             dict(stat="Family",     desc="TikTok reforzó Family Pairing para el control parental de screen-time.", source="TikTok · 2025"),
             dict(stat="Ms. Rachel", desc="Canales como Ms. Rachel se vuelven autoridad de aprendizaje temprano vía recomendación del feed.", source="TikTok / YouTube · 2025"),
         ],
         signals=[
             dict(png="macro-3-5-tiktok-learning-apps-kids.png",
                  caption="TikTok 'best learning apps for kids 2025' — la recomendación viral de MomTok sobre apps educativas.",
                  source="TikTok Discover · 2025",
                  url="https://www.tiktok.com/discover/best-learning-app-for-kids-2025"),
             dict(png="macro-3-5-youtube-msrachel.png",
                  caption="Ms. Rachel en YouTube — autoridad de aprendizaje temprano vía recomendación del feed materno.",
                  source="YouTube · 2025",
                  url="https://www.youtube.com/results?search_query=ms+rachel+toddler+learning+2025"),
             dict(png="macro-3-5-tiktok-family-pairing.png",
                  caption="TikTok Family Pairing — control parental de screen-time, respuesta de la plataforma al debate MomTok.",
                  source="TikTok · 2025",
                  url="https://www.tiktok.com/safety/en/guardians-guide/"),
         ]),
]

if __name__ == "__main__":
    build_deck(DIVIDERS, MICROS, SCREENSHOTS, OUTPUT)
